//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFlus
{
    using System;
    using System.Collections.Generic;

    public partial class Transaction
    {
        public int Id { get; set; }
        public int BankAccointId { get; set; }
        public int BankOperationId { get; set; }
        public string Addressee { get; set; }
        public string Description { get; set; }
        public double Amount { get; set; }
        public string Date { get; set; }
        public string IBAN { get; set; }
        public string OperationName { get; set; }

        public virtual BankAccount BankAccount { get; set; }
        public virtual BanksOperation BanksOperation { get; set; }
    }
}
